language: objective-c
osx_image: xcode8
xcode_project: CounterExample.xcodeproject
xcode_scheme: CounterExample
xcode_sdk: iphonesimulator10.0
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
install:
    - carthage bootstrap --no-use-binaries --platform iOS
#test